version: "3.6"

services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    tmpfs:
      - /data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      discovery.type: single-node
    container_name: elasticsearch
    tmpfs:
      - /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
