version: "3.6"

services:
  redis:
    image: redis:4-alpine
    container_name: redis
    tmpfs:
      - /data
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:4
    container_name: mongodb
    tmpfs:
      - /data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    tmpfs:
      - /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
