version: '3'

services:
  redis:
    image: redis:4-alpine
    container_name: redis
    tmpfs:
      - /data
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:3.6
    container_name: mongodb
    tmpfs:
      - /data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    tmpfs:
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"