before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

variables:
  DOCKER_DRIVER: overlay2

  DOCKER_BASH_IMAGE_SHA: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/docker-bash:$CI_COMMIT_SHA"
  DOCKER_BASH_IMAGE_BEFORE_SHA: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/docker-bash:$CI_COMMIT_BEFORE_SHA"

  BUILD_SERVER_IMAGE_LATEST: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/build-server:latest"
  BUILD_SERVER_IMAGE_SHA: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/build-server:$CI_COMMIT_SHA"
  BUILD_SERVER_IMAGE_BEFORE_SHA: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/build-server:$CI_COMMIT_BEFORE_SHA"

  BUILD_CLIENT_IMAGE_LATEST: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/build-client:latest"
  BUILD_CLIENT_IMAGE_SHA: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/build-client:$CI_COMMIT_SHA"
  BUILD_CLIENT_IMAGE_BEFORE_SHA: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/build-client:$CI_COMMIT_BEFORE_SHA"

  DIST_IMAGE_LATEST: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest"
  DIST_IMAGE_SHA: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
  DIST_IMAGE_SHA_BEFORE: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_BEFORE_SHA"

stages:
  - build:dependencies
  - build:application
  - pack

build:docker-bash:
  stage: build:dependencies
  image: docker:stable
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker pull $DOCKER_BASH_IMAGE_SHA || true
    - docker pull $DOCKER_BASH_IMAGE_BEFORE_SHA || true
    - docker build --pull -f ci/docker-bash.dockerfile --cache-from $DOCKER_BASH_IMAGE_SHA --cache-from $DOCKER_BASH_IMAGE_BEFORE_SHA --tag $DOCKER_BASH_IMAGE_SHA ci
    - docker push $DOCKER_BASH_IMAGE_SHA

build:server:
  stage: build:application
  image: $DOCKER_BASH_IMAGE_SHA
  tags:
    - docker
  services:
    - docker:dind
  script:
    - bash ci/build-image.sh -f ci/server.dockerfile -c $BUILD_SERVER_IMAGE_BEFORE_SHA -c $BUILD_SERVER_IMAGE_SHA -n $BUILD_SERVER_IMAGE_SHA -n $BUILD_SERVER_IMAGE_LATEST

build:client:
  stage: build:application
  image: $DOCKER_BASH_IMAGE_SHA
  tags:
    - docker
  services:
    - docker:dind
  script:
    - bash ci/build-image.sh -f ci/client.dockerfile -c $BUILD_CLIENT_IMAGE_BEFORE_SHA -c $BUILD_CLIENT_IMAGE_SHA -n $BUILD_CLIENT_IMAGE_SHA -n $BUILD_CLIENT_IMAGE_LATEST

.pack:dist:
  stage: pack
  image: $DOCKER_BASH_IMAGE_SHA
  tags:
    - docker
  services:
    - docker:dind
  script:
    - bash ci/pull-build-push.sh -f ci/dist.dockerfile -c $DIST_IMAGE_SHA_BEFORE -c $DIST_IMAGE_SHA -n -c $DIST_IMAGE_SHA -n -c $DIST_IMAGE_LATEST
    - bash ci/extract-from-image.sh $DIST_IMAGE_SHA /mediathekviewweb dist
  artifacts:
    paths:
      - dist
    expire_in: 3 months
